// ── Deliverable generators — grounded, cited, exportable ────────────────────
import type { Dossier, DeliverableMode } from "./types";
import { GRADE_MEANING } from "./grade";
import { polishMemo, aiEnabled } from "./ai";

const DISCLAIMER =
  "This dossier compiles publicly available government records and evidence-graded estimates with disclosed methodology and uncertainty. It is not a legal determination, an accusation of wrongdoing, or professional legal/financial advice. All modeled figures are Verity estimates, not reported or adjudicated values.";

const CONFLICT =
  "Conflict Disclosure: TerraRecore/TerraReFlow, affiliates of Verity, may be capable of providing services related to this pathway. Verity's findings are generated by documented public records and independent methodology; other qualified providers may also be considered.";

function usd(n?: number): string {
  if (n == null || isNaN(n)) return "—";
  const a = Math.abs(n);
  if (a >= 1e12) return `$${(n / 1e12).toFixed(2)}T`;
  if (a >= 1e9) return `$${(n / 1e9).toFixed(2)}B`;
  if (a >= 1e6) return `$${(n / 1e6).toFixed(1)}M`;
  if (a >= 1e3) return `$${(n / 1e3).toFixed(0)}K`;
  return `$${Math.round(n).toLocaleString()}`;
}

function header(d: Dossier, mode: DeliverableMode): string {
  const f = d.identify.facility;
  const title = mode === "litigation" ? "LITIGATION INTAKE MEMO" : "REMEDIATION & REDEVELOPMENT PATHWAY";
  return [
    `TERRA VERITY LEDGER — ${title}`,
    d.sampleData ? "*** SAMPLE DATA — NOT LIVE GOVERNMENT RECORDS ***" : "",
    `Site: ${f?.primaryName ?? d.input.query}`,
    `Registry ID: ${f?.registryId ?? "unresolved"}    Date: ${d.createdAt}    Overall grade: ${d.quantify.aggregateGrade ?? "—"}`,
    "",
  ].filter(Boolean).join("\n");
}

function evidenceIndex(d: Dossier): string {
  const lines = d.citations.map(
    (c, i) => `  [${i + 1}] ${c.sourceSystem}${c.recordId ? ` · ${c.recordId}` : ""} — ${c.sourceURL}`,
  );
  return ["EVIDENCE INDEX", ...(lines.length ? lines : ["  (no source records retrieved)"])].join("\n");
}

function documentedBlock(d: Dossier): string {
  const rows = d.quantify.documented.map(
    (l) => `  - ${l.category}: ${typeof l.value === "number" ? l.value.toLocaleString() : l.value}${l.unit ? " " + l.unit : ""}  [Grade ${l.evidenceGrade}] (${l.sourceSystem})`,
  );
  return ["DOCUMENTED CONTAMINATION & REGULATORY RECORD (real records)", ...(rows.length ? rows : ["  No documented records retrieved."]) ].join("\n");
}

function modeledBlock(d: Dossier): string {
  const rows = d.quantify.modeled.map(
    (m) => `  - ${m.category}: ${usd(m.estimateLow)} / ${usd(m.estimateExpected)} / ${usd(m.estimateHigh)} (low/expected/high)  [Grade D]\n      Basis: ${m.basis}`,
  );
  return [
    "VERITY MODELED ESTIMATE — not a reported or adjudicated figure. Grade D.",
    ...(rows.length ? rows : ["  No modeled estimate (insufficient documented inputs)."]),
  ].join("\n");
}

function actorChainBlock(d: Dossier): string {
  const rows = d.identify.actorChain.map(
    (a) => `  ${a.role} → ${a.name}${a.identifier ? ` (${a.identifier})` : ""}  [Grade ${a.evidenceGrade}, link conf ${(a.linkConfidence * 100).toFixed(0)}%] (${a.sourceSystem})`,
  );
  return ["RESPONSIBLE-PARTY CHAIN", ...(rows.length ? rows : ["  Chain unresolved."]) ].join("\n");
}

function litigationMemo(d: Dossier): string {
  const f = d.identify.financials;
  const disc = d.identify.disclosures.map((x) => `  - ${x.snippet} [${x.accession}]`);
  return [
    header(d, "litigation"),
    "1. SITE & FACILITY SUMMARY",
    `  ${d.identify.facility?.primaryName ?? d.input.query} — ${d.identify.facility?.address ?? "address unresolved"}`,
    `  FRS Registry ID: ${d.identify.facility?.registryId ?? "unresolved"}`,
    "",
    "2. " + actorChainBlock(d),
    f.available
      ? `  Deep-pocket parent: ${f.entityName} (CIK ${f.cik}) — revenue ${usd(f.revenue)}, assets ${usd(f.totalAssets)}, liabilities ${usd(f.totalLiabilities)} (FY ${f.fiscalYear ?? "—"}).`
      : `  Financial capacity: ${f.note ?? "not publicly available (party may be private)."}`,
    "",
    "3. " + documentedBlock(d),
    "",
    "4. RELEVANT PUBLIC DISCLOSURES (10-K, cited by accession)",
    ...(disc.length ? disc : ["  No 10-K disclosures matched this site."]),
    "",
    "5. " + modeledBlock(d),
    "",
    "6. " + evidenceIndex(d),
    "",
    "7. EVIDENCE CONFIDENCE & GAPS",
    `  Aggregate grade: ${d.quantify.aggregateGrade ?? "—"} — ${d.quantify.aggregateGrade ? GRADE_MEANING[d.quantify.aggregateGrade] : "no records"}.`,
    ...(d.gaps.length ? d.gaps.map((g) => `  - GAP: ${g}`) : ["  - No gaps flagged."]),
    "",
    "DISCLAIMER",
    "  " + DISCLAIMER,
  ].join("\n");
}

function remediationMemo(d: Dossier): string {
  const providers = [
    "Government-led (state/EPA program)",
    "Remediation contractors",
    "Environmental engineering firms",
    "Environmental consultants",
    "Infrastructure developers",
    "TerraRecore / TerraReFlow (affiliate)",
  ];
  const funding = [
    "EPA RE-Powering America's Land (siting on contaminated/brownfield land)",
    "EPA Brownfields Assessment/Cleanup grants",
    "State voluntary cleanup / remediation funds",
    "CERCLA cost-recovery from responsible parties",
  ];
  return [
    header(d, "remediation"),
    "1. SITE & CONTAMINATION PROFILE",
    `  ${d.identify.facility?.primaryName ?? d.input.query} — ${d.identify.facility?.address ?? "address unresolved"} (FRS ${d.identify.facility?.registryId ?? "unresolved"})`,
    "  " + documentedBlock(d).replace(/\n/g, "\n  "),
    "",
    "2. " + modeledBlock(d),
    "",
    "3. REGULATORY POSTURE",
    ...d.quantify.documented
      .filter((l) => /superfund|npl|rcra|compliance|enforcement|penalt/i.test(l.category))
      .map((l) => `  - ${l.category}: ${l.value} [Grade ${l.evidenceGrade}] (${l.sourceSystem})`),
    "",
    "4. REDEVELOPMENT & FUNDING PATHWAYS",
    ...funding.map((x) => `  - ${x}`),
    "",
    "5. RESTORATION / REMEDIATION PROVIDER OPTIONS",
    ...providers.map((x) => `  - ${x}`),
    "",
    "6. RECOMMENDED NEXT STEPS",
    "  - Validate any unconfirmed responsible-party links against public records.",
    "  - Commission a Phase II site assessment to convert modeled estimates to engineered costs.",
    "  - Engage the applicable state cleanup program and evaluate brownfield funding eligibility.",
    "",
    "7. " + evidenceIndex(d),
    "",
    "DISCLAIMER",
    "  " + DISCLAIMER,
    "",
    CONFLICT,
  ].join("\n");
}

export async function generateDeliverable(
  mode: DeliverableMode,
  dossier: Dossier,
  opts: { aiPolish?: boolean } = {},
): Promise<{ title: string; body: string; polished: boolean }> {
  const structured = mode === "litigation" ? litigationMemo(dossier) : remediationMemo(dossier);
  const title = mode === "litigation" ? "Litigation Intake Memo" : "Remediation & Redevelopment Pathway";
  if (opts.aiPolish && aiEnabled()) {
    const polished = await polishMemo(structured);
    if (polished) return { title, body: polished, polished: true };
  }
  return { title, body: structured, polished: false };
}
